CREATE TABLE location (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY,
  name        VARCHAR(255) NOT NULL,
  description VARCHAR(255),
  PRIMARY KEY (id)
);
CREATE INDEX location_name_idx on location (name);